---@meta

---@class UABP_CH_MeshBase_C : UAnimInstanceCore
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_CopyBone_61 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_60 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_59 FAnimNode_CopyBone
---@field AnimGraphNode_ComponentToLocalSpace_46 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_45 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_44 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_43 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_42 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_41 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_40 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_39 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_38 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_37 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_36 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_35 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_34 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_33 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LinkedInputPose_8 FAnimNode_LinkedInputPose
---@field AnimGraphNode_SaveCachedPose_21 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_77 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_76 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_44 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_75 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_43 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_74 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_42 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_73 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_41 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_72 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_40 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_71 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_39 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_70 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_38 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_69 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_37 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_68 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_36 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_67 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_35 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_66 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_34 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_65 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_33 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_64 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_32 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_63 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_31 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_62 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_30 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_61 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_29 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SaveCachedPose_20 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByInt_1 FAnimNode_BlendListByInt
---@field AnimGraphNode_ComponentToLocalSpace_32 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_31 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_30 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_29 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_28 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_27 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_26 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_25 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_24 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_23 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_22 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_21 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_20 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_19 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_18 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_17 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_28 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_27 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_26 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_25 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_24 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_23 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_22 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_21 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_20 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_19 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_18 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_17 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_16 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_15 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_14 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LocalToComponentSpace_13 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_60 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_59 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_58 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_57 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_56 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_55 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_54 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_53 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_52 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_51 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_50 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_49 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_48 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_47 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_46 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_45 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_44 FAnimNode_UseCachedPose
---@field AnimGraphNode_CopyBone_58 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_57 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_56 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_55 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_54 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_53 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_52 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_51 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_50 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_49 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_48 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_47 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_46 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_45 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_44 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_43 FAnimNode_CopyBone
---@field AnimGraphNode_Root_10 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_7 FAnimNode_LinkedInputPose
---@field AnimGraphNode_RotationMultiplier_13 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_12 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_11 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_10 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_9 FAnimNode_RotationMultiplier
---@field AnimGraphNode_BoneDrivenController_3 FAnimNode_BoneDrivenController
---@field AnimGraphNode_BoneDrivenController_2 FAnimNode_BoneDrivenController
---@field AnimGraphNode_CopyBone_42 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_41 FAnimNode_CopyBone
---@field AnimGraphNode_BoneDrivenController_1 FAnimNode_BoneDrivenController
---@field AnimGraphNode_BoneDrivenController FAnimNode_BoneDrivenController
---@field AnimGraphNode_TwoBoneIK_5 FAnimNode_TwoBoneIK
---@field AnimGraphNode_CopyBone_40 FAnimNode_CopyBone
---@field AnimGraphNode_Constraint_3 FAnimNode_Constraint
---@field AnimGraphNode_TwoBoneIK_4 FAnimNode_TwoBoneIK
---@field AnimGraphNode_LocalToComponentSpace_12 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_RotationMultiplier_8 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_7 FAnimNode_RotationMultiplier
---@field AnimGraphNode_CopyBone_39 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_38 FAnimNode_CopyBone
---@field AnimGraphNode_Constraint_2 FAnimNode_Constraint
---@field AnimGraphNode_SaveCachedPose_19 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_18 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_16 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_CopyBone_37 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_36 FAnimNode_CopyBone
---@field AnimGraphNode_ComponentToLocalSpace_15 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_17 FAnimNode_SaveCachedPose
---@field AnimGraphNode_CopyBone_35 FAnimNode_CopyBone
---@field AnimGraphNode_SaveCachedPose_16 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_14 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_43 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_11 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_42 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_10 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_CopyBone_34 FAnimNode_CopyBone
---@field AnimGraphNode_ComponentToLocalSpace_13 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_12 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ComponentToLocalSpace_11 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_RotationMultiplier_6 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_5 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_4 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_3 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier_2 FAnimNode_RotationMultiplier
---@field AnimGraphNode_SaveCachedPose_15 FAnimNode_SaveCachedPose
---@field AnimGraphNode_CopyBone_33 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_32 FAnimNode_CopyBone
---@field AnimGraphNode_ComponentToLocalSpace_10 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_CopyBone_31 FAnimNode_CopyBone
---@field AnimGraphNode_LocalToComponentSpace_9 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_41 FAnimNode_UseCachedPose
---@field AnimGraphNode_RotationMultiplier_1 FAnimNode_RotationMultiplier
---@field AnimGraphNode_RotationMultiplier FAnimNode_RotationMultiplier
---@field AnimGraphNode_ComponentToLocalSpace_9 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_CopyBone_30 FAnimNode_CopyBone
---@field AnimGraphNode_LocalToComponentSpace_8 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_40 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_8 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_14 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByInt FAnimNode_BlendListByInt
---@field AnimGraphNode_Root_9 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_6 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_8 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_5 FAnimNode_LinkedInputPose
---@field AnimGraphNode_LocalToComponentSpace_7 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_Root_7 FAnimNode_Root
---@field AnimGraphNode_CopyBone_29 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_28 FAnimNode_CopyBone
---@field AnimGraphNode_LinkedInputPose_4 FAnimNode_LinkedInputPose
---@field AnimGraphNode_CopyBone_27 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_26 FAnimNode_CopyBone
---@field AnimGraphNode_TwoBoneIK_3 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_2 FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone_11 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_10 FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace_7 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ModifyBone_9 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_8 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_7 FAnimNode_ModifyBone
---@field AnimGraphNode_CopyBone_25 FAnimNode_CopyBone
---@field AnimGraphNode_ModifyBone_6 FAnimNode_ModifyBone
---@field AnimGraphNode_CopyBone_24 FAnimNode_CopyBone
---@field AnimGraphNode_ModifyBone_5 FAnimNode_ModifyBone
---@field AnimGraphNode_Constraint_1 FAnimNode_Constraint
---@field AnimGraphNode_Constraint FAnimNode_Constraint
---@field AnimGraphNode_CopyBone_23 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_22 FAnimNode_CopyBone
---@field AnimGraphNode_Root_6 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_3 FAnimNode_LinkedInputPose
---@field AnimGraphNode_SaveCachedPose_13 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_18 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_39 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_17 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_38 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_16 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_37 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_15 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_36 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_14 FAnimNode_Slot
---@field AnimGraphNode_Slot_13 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_35 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_17 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_12 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_34 FAnimNode_UseCachedPose
---@field AnimGraphNode_Root_5 FAnimNode_Root
---@field AnimGraphNode_BlendBoneByChannel_3 FAnimNode_BlendBoneByChannel
---@field AnimGraphNode_LinkedInputPose_2 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_4 FAnimNode_Root
---@field AnimGraphNode_UseCachedPose_33 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_16 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_32 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_31 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_30 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_29 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_28 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_12 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendBoneByChannel_2 FAnimNode_BlendBoneByChannel
---@field AnimGraphNode_LayeredBoneBlend_15 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendBoneByChannel_1 FAnimNode_BlendBoneByChannel
---@field AnimGraphNode_LayeredBoneBlend_14 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_11 FAnimNode_Slot
---@field AnimGraphNode_Slot_10 FAnimNode_Slot
---@field AnimGraphNode_Slot_9 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_27 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_26 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_11 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_25 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_24 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_23 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_8 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_13 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_12 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_11 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_10 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_22 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_9 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_21 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_8 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_7 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LinkedInputPose_1 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_3 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_2 FAnimNode_Root
---@field AnimGraphNode_LayeredBoneBlend_6 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_20 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_19 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_5 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_18 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_17 FAnimNode_UseCachedPose
---@field AnimGraphNode_Root_1 FAnimNode_Root
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_Slot_7 FAnimNode_Slot
---@field AnimGraphNode_Slot_6 FAnimNode_Slot
---@field AnimGraphNode_Inertialization FAnimNode_Inertialization
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_ModifyCurve_5 FAnimNode_ModifyCurve
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_ModifyCurve_4 FAnimNode_ModifyCurve
---@field AnimGraphNode_SequenceEvaluator_4 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_ModifyCurve_3 FAnimNode_ModifyCurve
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_ModifyCurve_2 FAnimNode_ModifyCurve
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequenceEvaluator_3 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_TwoWayBlend_2 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequenceEvaluator_2 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_TwoWayBlend_1 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_ModifyCurve_1 FAnimNode_ModifyCurve
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_6 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_6 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_4 FAnimNode_ModifyBone
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_ApplyAdditive_11 FAnimNode_ApplyAdditive
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_ModifyCurve FAnimNode_ModifyCurve
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequenceEvaluator_1 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SequenceEvaluator FAnimNode_SequenceEvaluator
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_ComponentToLocalSpace_5 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LinkedAnimLayer_9 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_8 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_7 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_6 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_Slot_5 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_4 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_4 FAnimNode_Slot
---@field AnimGraphNode_ApplyAdditive_10 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive_9 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive_8 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_ApplyAdditive_7 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive_6 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_LocalToComponentSpace_5 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_4 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LinkedAnimLayer_5 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_ModifyBone_3 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_4 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_ApplyAdditive_5 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_ApplyAdditive_4 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive_3 FAnimNode_ApplyAdditive
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_LinkedAnimLayer_4 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_ComponentToLocalSpace_3 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_RotationOffsetBlendSpace_1 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_LinkedAnimLayer_3 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_ApplyAdditive_2 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_LinkedAnimLayer_2 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_CopyBone_21 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_20 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_19 FAnimNode_CopyBone
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendBoneByChannel FAnimNode_BlendBoneByChannel
---@field AnimGraphNode_ApplyAdditive_1 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_LocalToComponentSpace_3 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_2 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_LinkedAnimLayer_1 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LocalToComponentSpace_2 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LookAt_1 FAnimNode_LookAt
---@field AnimGraphNode_CopyBone_18 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_17 FAnimNode_CopyBone
---@field AnimGraphNode_LookAt FAnimNode_LookAt
---@field AnimGraphNode_CopyBone_16 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_15 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_14 FAnimNode_CopyBone
---@field AnimGraphNode_LinkedAnimLayer FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_CopyBone_13 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_12 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_11 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_10 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_9 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_8 FAnimNode_CopyBone
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_CopyBone_7 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_6 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_5 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_4 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_3 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_2 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_1 FAnimNode_CopyBone
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_CopyBone FAnimNode_CopyBone
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AimingRotation FRotator
---@field Velocity FVector
---@field RelativeVelocityDirection FVector
---@field Acceleration FVector
---@field MovementInput FVector
---@field IsMoving boolean
---@field HasMovementInput boolean
---@field Speed float
---@field MovementInputAmount float
---@field GroundedEntryState GroundedEntryState::Type
---@field MovementDirection MovementDirection::Type
---@field TrackedHipsDirection HipsDirection::Type
---@field RelativeAccelerationAmount FVector
---@field ShouldMove boolean
---@field Rotate_L boolean
---@field Rotate_R boolean
---@field Pivot boolean
---@field RotateRate float
---@field RotationScale float
---@field DiagonalScaleAmount float
---@field WalkRunBlend float
---@field LocomotionPlayStartPos float
---@field EventLocomotionPlayStartPos float
---@field LocomotionPlayRate float
---@field CrouchingPlayRate float
---@field StrideBlend float
---@field VelocityBlend FVelocityBlend
---@field LeanAmount FLeanAmount
---@field DiagonalScaleAmountCurve UCurveFloat
---@field StrideBlend_N_Walk UCurveFloat
---@field StrideBlend_N_Run UCurveFloat
---@field StrideBlend_C_Walk UCurveFloat
---@field SmoothedAimingRotation FRotator
---@field SpineRotation FRotator
---@field AimingAngle FVector2D
---@field SmoothedAimingAngle FVector2D
---@field AimSweepTime float
---@field AimYawRate float
---@field ZoomAmount float
---@field Jumped boolean
---@field JumpPlayRate float
---@field FallSpeed float
---@field LandPrediction float
---@field LandPredictionCurve UCurveFloat
---@field LeanInAirCurve UCurveFloat
---@field OverlayOverrideState int32
---@field Enable_AimOffset float
---@field FootLock_L_Alpha float
---@field FootLock_R_Alpha float
---@field FootLock_L_Location FVector
---@field FootLock_R_Location FVector
---@field FootLock_L_Rotation FRotator
---@field FootLock_R_Rotation FRotator
---@field FootOffset_L_Location FVector
---@field FootOffset_R_Location FVector
---@field FootOffset_L_Rotation FRotator
---@field FootOffset_R_Rotation FRotator
---@field PelvisOffset FVector
---@field PelvisAlpha float
---@field Character ACharacter
---@field DeltaTimeX float
---@field TurnCheckMinAngle float
---@field Turn180Threshold float
---@field AimYawRateLimit float
---@field ElapsedDelayTime float
---@field MovementState ALS_MovementState::Type
---@field PrevMovementState ALS_MovementState::Type
---@field MovementAction ALS_MovementAction::Type
---@field RotationMode ALS_RotationMode::Type
---@field Gait ALS_Gait::Type
---@field Stance ALS_Stance::Type
---@field ViewMode ALS_ViewMode::Type
---@field OverlayState ALS_OverlayState::Type
---@field BasePose_N float
---@field BasePose_CLF float
---@field Arm_L float
---@field Arm_L_Add float
---@field Arm_L_LS float
---@field Arm_L_MS float
---@field Arm_R float
---@field Arm_R_Add float
---@field Arm_R_LS float
---@field Arm_R_MS float
---@field LayeringHand_L_Alpha float
---@field LayeringHand_R_Alpha float
---@field Legs float
---@field Legs_Add float
---@field Pelvis float
---@field Pelvis_Add float
---@field Spine float
---@field Spine_Add float
---@field Head float
---@field Head_Add float
---@field YawOffset_FB UCurveVector
---@field YawOffset_LR UCurveVector
---@field FYaw float
---@field BYaw float
---@field LYaw float
---@field RYaw float
---@field InputYawOffsetTime float
---@field ForwardYawTime float
---@field LeftYawTime float
---@field RightYawTime float
---@field MinAngleDelay float
---@field MaxAngleDelay float
---@field RotateMinThreshold float
---@field RotateMaxThreshold float
---@field AimYawRateMinRange float
---@field AimYawRateMaxRange float
---@field MinPlayRate float
---@field MaxPlayRate float
---@field FlailRate float
---@field Enable_HandIK_L float
---@field Enable_HandIK_R float
---@field AnimatedWalkSpeed float
---@field AnimatedRunSpeed float
---@field AnimatedSprintSpeed float
---@field AnimatedCrouchSpeed float
---@field VelocityBlendInterpSpeed float
---@field GroundedLeanInterpSpeed float
---@field InAirLeanInterpSpeed float
---@field SmoothedAimingRotationInterpSpeed float
---@field InputYawOffsetInterpSpeed float
---@field TriggerPivotSpeedLimit float
---@field FootHeight float
---@field IK_TraceDistanceAboveFoot float
---@field IK_TraceDistanceBelowFoot float
---@field LipSync_A float
---@field LipSync_I float
---@field LipSync_U float
---@field LipSync_E float
---@field LipSync_O float
---@field bBlink boolean
---@field bNoBlink boolean
---@field EyeLookatAlpha float
---@field EyeLookat_Horizontal float
---@field EyeLookat_Vertical float
---@field FaceDeformAlpha float
---@field FaceAngleRatio_Horizontal float
---@field FaceAngleRatio_Vertical float
---@field PawnOwner APawn
---@field LookAtInterpSpeed float
---@field BodyLookat_Horizontal float
---@field BodyLookatOffset_Horizontal float
---@field BodyLookat_Vertical float
---@field BodyLookatOffset_Vertical float
---@field EyeLookatOffset_Horizontal float
---@field EyeLookatOffset_Vertical float
---@field LookAtType EEvtCharaAnimationLookAtType
---@field LookAtTargetActor AActor
---@field LookAtTargetActorBoneName FString
---@field LookAtWorldLocation FVector
---@field LookAtFinalTargetLocation FVector
---@field bForceEyeClose boolean
---@field BlinkWait float
---@field BlinkContinuousNumber uint8
---@field SaccadePos FVector
---@field SaccadeRandomVec FVector
---@field SaccadeWait float
---@field SaccadeAlpha float
---@field leftLegSkirtBS FVector2D
---@field RightLegSkirtBS FVector2D
---@field skirtRootRot FRotator
---@field rotate0to360 float
---@field PhysicsAlpha float
---@field SpringStiffness float
---@field HipOffset_Adjust FVector
---@field IK_FootOffset_L_Adjust_Alpha float
---@field IK_FootOffset_R_Adjust_Alpha float
---@field BodyLookatAlpha float
---@field Enable_FootIK_L float
---@field Enable_FootIK_R float
---@field IK_Alpha float
---@field IK_UpperBody_Alpha float
---@field IK_LowerBody_Alpha float
---@field L_ExUpleg_00_modfyTRANSX FVector
---@field R_ExUpLeg_00_modfyTRANSX FVector
---@field L_KneeCap_00_modfyTRANS FVector
---@field R_KneeCap_00_modfyTRANS FVector
---@field ForeArmTwist02Exists boolean
---@field LipSync_Total float
---@field AddBreathAlpha float
---@field PhysicsAlpha_UpperBody float
---@field PhysicsAlpha_LowerBody float
---@field AddSittingBreathAlpha float
---@field WaitPoseWaitTime float
---@field InWaitPoseState boolean
---@field EyeLookAt_WithLookTarget boolean
---@field BodyLookAt_EnableLimitter boolean
---@field EventPhysics xrd777_EventPhysics::Type
---@field FaceDistanceRatio float
---@field IKTargetNameList TArray<FName>
---@field EventFootIKAlpha float
---@field EventPelvisLockAlpha float
---@field EventPelvisTransform FVector
---@field SceneCommpornent USceneComponent
---@field HandIK_R_Transform FTransform
---@field HandIK_L_Transform FTransform
---@field LookatOverrideAlpha float
---@field PhysicsAlpha_Skirt float
---@field PhysicsAlpha_Hair float
---@field PhysicsAlpha_Jacket float
---@field AdjustSinking float
---@field CollisionHalfHeight float
---@field HandTargetVar_R float
---@field HandTargetVar_L float
---@field CurrentHandTargetVar_R float
---@field CurrentHandTargetVar_L float
---@field WalkSpeed_Threshold float
---@field RunSpeed_Threshold float
---@field SprintSpeed_Threshold float
---@field LockFoot_R_Alpha float
---@field LockFoot_L_Alpha float
---@field ApplyPhysicsAlpha float
---@field ApplyPhysicsAlphaUpperBody float
---@field ApplyPhysicsAlphaLowerBody float
---@field ApplyPhysicsAlphaHair float
---@field ApplyPhysicsAlphaJacket float
---@field ApplyPhysicsAlphaSkirt float
---@field EventStrideBlend float
---@field ApplyStrideBlend float
---@field OverrideLocomotionAnim UBlendSpace
---@field OverrideLocomotionAnimEnable boolean
---@field OverrideLocomotionNotMoveAnim UAnimSequence
---@field EnableOverrideLocomotionNotMoveAnim boolean
---@field test_arrow UArrowComponent
---@field lookatArrow UArrowComponent
---@field Is_EventLocomotionSim boolean
---@field EnableLookatNewFunction boolean
---@field EnableLookatTypeIsWorldNewFunction boolean
---@field ChangedWalkRunBlend boolean
---@field LocomotionStopAlpha float
---@field LocomotionStopPlayRate float
---@field MovingTime float
---@field RunningTime float
---@field WalkingTime float
---@field UpdateWalkRunIntervalTime float
---@field PreserveRunningState boolean
---@field LocomotionStopped boolean
---@field EnterLocomotionOverride boolean
---@field PresearveWalkRunBlend float
---@field PreviousWalkRunState float
---@field IsInPocket boolean
---@field WalkInterval boolean
---@field IsApplyingFootIK boolean
---@field AssistanceBone_L_Alpha float
---@field AssistanceBone_R_Alpha float
---@field EnableGoToMainWaitPose boolean
---@field LockAttachHand_R_Transform_Alpha float
---@field LockAttachHand_L_Transform_Alpha float
---@field LayeringLegs_Alpha float
---@field LayeringHead_Alpha float
---@field LockBelowHips_Alpha float
---@field ApplyPellvisLockAlpha float
---@field ApplyAddSittingBreathAlpha float
---@field ApplyAddBreathAlpha float
---@field FaceDistanceAlpha float
---@field BaseSkeletonMesh USkeletalMeshComponent
---@field PostProcessInstances TArray<TSubclassOf<UAnimInstance>>
---@field EnablePostProcessABP boolean
---@field Enable_LayeringArms boolean
---@field AdjustFootIKPV_L_Alpha float
---@field AdjustFootIKPV_R_Alpha float
---@field ApplyWalkRunBlend float
---@field Event_Arms_L_Alpha float
---@field Event_Arms_R_Alpha float
---@field Disable_LookatSpine_Alpha float
---@field PelvisTarget_Z float
---@field Foot_L_TargetDistance float
---@field Foot_R_TargetDistance float
---@field Foot_L_TargetRotation FRotator
---@field Foot_R_TargetRotation FRotator
---@field Previous_Foot_L_Location FVector
---@field Previous_Foot_R_Location FVector
---@field Goto_NeautralPose boolean
---@field Update_Foot_L boolean
---@field Update_Foot_R boolean
---@field Previous_Lookat_Horizontal float
---@field Previous_Speed float
---@field ActorSinking_L float
---@field ActorSinking_R float
---@field Current_Foot_L_Location FVector
---@field Current_Foot_R_Location FVector
---@field ActorBottomDistance float
---@field Apply_IK_UpperBody_Alpha float
---@field Apply_IK_LowerBody_Alpha float
---@field StrideBlendDash_Alpha float
---@field TempSpeed float
---@field CurrentLocomotionState Enum_LocomotionState::Type
---@field PreviousLocomotionState Enum_LocomotionState::Type
---@field Disable_InWaitPose boolean
---@field Anim_BlendStopPose UAnimSequence
---@field Toggle_StopBlendPose boolean
---@field Goto_MainWaitPose boolean
---@field NoCopy_AttachShoulderFromUpperBodySlot float
---@field Copy_SkirtFromUpperBodySlot float
---@field NoCopy_AttachLowerFromUpperBodySlot float
---@field Apply_MeandelingOffset_Y float
---@field NoCopy_LeftArmFromUpperBodySlot float
---@field LegsAnimBlendW float
---@field AddBleath_StartPos float
---@field ForwardFloorState Enum_FloorState::Type
---@field WaitPoseTime float
---@field CurrentActorLocation FVector
---@field CurrentActorRotation FRotator
---@field Disable_Physics boolean
---@field Interp_HairLookat_H float
---@field Interp_HairLookat_V float
---@field NoBlink_fromCurve boolean
---@field Has_HitFootIK boolean
local UABP_CH_MeshBase_C = {}

---@param OutLocomotionState Enum_LocomotionState::Type
function UABP_CH_MeshBase_C:GetLocomotionState(OutLocomotionState) end
---@param OutWalkRunBlend float
---@param OutPreviousWalkRunBlend float
function UABP_CH_MeshBase_C:GetWalkRunBlend(OutWalkRunBlend, OutPreviousWalkRunBlend) end
---@param Out_foot_r boolean
---@param Out_foot_l boolean
function UABP_CH_MeshBase_C:Get_Enable_FootIK(Out_foot_r, Out_foot_l) end
---@param Return UAnimInstance
function UABP_CH_MeshBase_C:Get_AnimBP(Return) end
---@param LookAtHorizontal float
---@param LookAtVertical float
---@param Out_Interp_LookatHair_H float
---@param Out_Interp_LookatHair_V float
---@param PhysicsAlpha_Out float
---@param PhysicsAlpha_Upperbody_Out float
---@param PhysicsAlpha_Lowerbody_Out float
---@param PhysicsAlpha_Hair_Out float
---@param PhysicsAlpha_Jacket_Out float
---@param PhysicsAlpha_Skirt_Out float
function UABP_CH_MeshBase_C:Get_ABP_CH_MeshBaseVariable(LookAtHorizontal, LookAtVertical, Out_Interp_LookatHair_H, Out_Interp_LookatHair_V, PhysicsAlpha_Out, PhysicsAlpha_Upperbody_Out, PhysicsAlpha_Lowerbody_Out, PhysicsAlpha_Hair_Out, PhysicsAlpha_Jacket_Out, PhysicsAlpha_Skirt_Out) end
---@param InPhysPose FPoseLink
---@param HairPhysLayer FPoseLink
function UABP_CH_MeshBase_C:HairPhysLayer(InPhysPose, HairPhysLayer) end
---@param InMeshPose FPoseLink
---@param HairAdjustLayer FPoseLink
function UABP_CH_MeshBase_C:HairAdjustLayer(InMeshPose, HairAdjustLayer) end
---@param InMeshPose FPoseLink
---@param CostumeAdjustLayer FPoseLink
function UABP_CH_MeshBase_C:CostumeAdjustLayer(InMeshPose, CostumeAdjustLayer) end
---@param InPose FPoseLink
---@param CustomAdditiveLayer FPoseLink
function UABP_CH_MeshBase_C:CustomAdditiveLayer(InPose, CustomAdditiveLayer) end
---@param InPhysicsPose FPoseLink
---@param CostumePhysLayer FPoseLink
function UABP_CH_MeshBase_C:CostumePhysLayer(InPhysicsPose, CostumePhysLayer) end
---@param InPose_1 FPoseLink
---@param Set_AttachHandIK_Bone FPoseLink
function UABP_CH_MeshBase_C:Set_AttachHandIK_Bone(InPose_1, Set_AttachHandIK_Bone) end
---@param InPose_0 FPoseLink
---@param AssistanceBone FPoseLink
function UABP_CH_MeshBase_C:AssistanceBone(InPose_0, AssistanceBone) end
---@param InPose FPoseLink
---@param Foot_IK FPoseLink
UABP_CH_MeshBase_C['Foot IK'] = function(self, InPose, Foot_IK) end
---@param Base_Layer_Input FPoseLink
---@param LayerBlending FPoseLink
function UABP_CH_MeshBase_C:LayerBlending(Base_Layer_Input, LayerBlending) end
---@param BaseLayer FPoseLink
function UABP_CH_MeshBase_C:BaseLayer(BaseLayer) end
---@param AnimGraph FPoseLink
function UABP_CH_MeshBase_C:AnimGraph(AnimGraph) end
---@param InCurveName FName
---@param InHandTargetVar float
---@param Out_IndexHandTarget float
---@param is_update boolean
function UABP_CH_MeshBase_C:Get_IndexHandIK(InCurveName, InHandTargetVar, Out_IndexHandTarget, is_update) end
---@param Return boolean
UABP_CH_MeshBase_C['Can Enable Post Process In Event'] = function(self, Return) end
---@param Result Enum_FloorState::Type
UABP_CH_MeshBase_C['Get Floor State'] = function(self, Result) end
function UABP_CH_MeshBase_C:Set_IsEnableLocomotionSim() end
UABP_CH_MeshBase_C['Set Actor Bottom Distance'] = function(self, ) end
---@param In_ActorSinking float
---@param In_Foot_L_Distance float
---@param In_Foot_R_Distance float
---@param In_Foot_L_Rotation FRotator
---@param In_Foot_R_Rotation FRotator
function UABP_CH_MeshBase_C:Set_FootDistance(In_ActorSinking, In_Foot_L_Distance, In_Foot_R_Distance, In_Foot_L_Rotation, In_Foot_R_Rotation) end
function UABP_CH_MeshBase_C:Check_UpdateFootIK() end
function UABP_CH_MeshBase_C:IsLookatUpdate() end
---@param ArmL_R_Alpha float
UABP_CH_MeshBase_C['Get Layering Arms Alpha'] = function(self, ArmL_R_Alpha) end
UABP_CH_MeshBase_C['Update AddBleath Values'] = function(self, ) end
UABP_CH_MeshBase_C['Update Locomotion Values'] = function(self, ) end
---@param InStartLocation FVector
---@param InStartRotation FRotator
---@param InTargetLocation FVector
---@param OutHorizontalAngle float
---@param OutVerticalAngle float
function UABP_CH_MeshBase_C:CulcLookatDirection_Vector(InStartLocation, InStartRotation, InTargetLocation, OutHorizontalAngle, OutVerticalAngle) end
---@param InStartLocation FVector
---@param InTargetLocation FVector
---@param OutHorizontalAngle float
---@param OutVerticalAngle float
function UABP_CH_MeshBase_C:CulcLookatDirection_Euler(InStartLocation, InTargetLocation, OutHorizontalAngle, OutVerticalAngle) end
UABP_CH_MeshBase_C['Update Lock Body'] = function(self, ) end
function UABP_CH_MeshBase_C:UpdatePhysicsAlpha() end
---@param InCurveName FName
---@param InHandName FName
---@param InHandTargetVar float
---@param InCurrentHandTargetVar float
---@param OutHandTargetTransform FTransform
function UABP_CH_MeshBase_C:GetTargetHandIK(InCurveName, InHandName, InHandTargetVar, InCurrentHandTargetVar, OutHandTargetTransform) end
UABP_CH_MeshBase_C['Update IK Values'] = function(self, ) end
function UABP_CH_MeshBase_C:SetHandIK() end
---@param InAdjustSinking float
---@param InEnableFootIK_L boolean
---@param InEnableFootIK_R boolean
---@param IsUpdate_Foot_L boolean
---@param IsUpdate_Foot_R boolean
---@param OutActorSinking float
---@param OutFootL_Distance float
---@param OutFootR_Distance float
---@param OutFootL_Rotation FRotator
---@param OutFootR_Rotation FRotator
UABP_CH_MeshBase_C['Get Foot Offsets'] = function(self, InAdjustSinking, InEnableFootIK_L, InEnableFootIK_R, IsUpdate_Foot_L, IsUpdate_Foot_R, OutActorSinking, OutFootL_Distance, OutFootR_Distance, OutFootL_Rotation, OutFootR_Rotation) end
---@param TraceLimit float
---@param InActorBottomDistance float
---@param TraceStartLocation FVector
---@param OutHitResult boolean
---@param OutHitDistance float
---@param OutHitRotation FRotator
UABP_CH_MeshBase_C['Foot Trace'] = function(self, TraceLimit, InActorBottomDistance, TraceStartLocation, OutHitResult, OutHitDistance, OutHitRotation) end
---@param BodyLookAt_EnableLimitter boolean
---@param MinAngleDegrees float
---@param MaxAngleDegrees float
---@param LookAtTarget float
---@param LookatOffset float
---@return float
function UABP_CH_MeshBase_C:ClampAngleToLookat(BodyLookAt_EnableLimitter, MinAngleDegrees, MaxAngleDegrees, LookAtTarget, LookatOffset) end
---@return FString
function UABP_CH_MeshBase_C:GetLookAtTargetActorBoneName() end
---@return FVector
function UABP_CH_MeshBase_C:GetLookAtWorldLocation() end
---@return uint8
function UABP_CH_MeshBase_C:GetLookAtType() end
---@return AActor
function UABP_CH_MeshBase_C:GetLookAtTargetActor() end
---@param HeadBoneName FName
---@param SKMesh USkeletalMeshComponent
---@param Camera APlayerCameraManager
function UABP_CH_MeshBase_C:FaceDeformationAtCamera(HeadBoneName, SKMesh, Camera) end
---@param DriveBone FName
---@param Target USceneComponent
---@param transformX FVector
function UABP_CH_MeshBase_C:GetKneeCapTransXY(DriveBone, Target, transformX) end
---@param DriveBone FName
---@param Target USceneComponent
---@param transformX FVector
UABP_CH_MeshBase_C['Get Ex Upleg TransX'] = function(self, DriveBone, Target, transformX) end
function UABP_CH_MeshBase_C:ClampAllLookatAngle() end
---@param Lookat_Vertical_ float
---@param Lookat_Horizontal_ float
---@param TargetLookat_Vertical_ float
---@param TargetLookat_Horizontal_ float
---@param DeltaTime_ float
---@param InterpSpeed_ float
---@param Lookat_CurrentVertical float
---@param Lookat_CurrentHorizontal float
function UABP_CH_MeshBase_C:InterpLookAtTo(Lookat_Vertical_, Lookat_Horizontal_, TargetLookat_Vertical_, TargetLookat_Horizontal_, DeltaTime_, InterpSpeed_, Lookat_CurrentVertical, Lookat_CurrentHorizontal) end
---@param CurrentAngle float
---@param AngleOverLimitter boolean
---@param AngleLimit float
---@param ClampAngle float
function UABP_CH_MeshBase_C:ClampLookAtAngle(CurrentAngle, AngleOverLimitter, AngleLimit, ClampAngle) end
---@param CharaBP ABP_CharacterBase_C
---@param DeltaTime float
---@param InterpSpeed float
function UABP_CH_MeshBase_C:Lookat(CharaBP, DeltaTime, InterpSpeed) end
---@param DeltaTime float
function UABP_CH_MeshBase_C:EyeSaccade(DeltaTime) end
---@param DeltaTime float
function UABP_CH_MeshBase_C:EyeBlink(DeltaTime) end
function UABP_CH_MeshBase_C:ResetIKOffsets() end
---@param Angle float
---@param MinAngle float
---@param MaxAngle float
---@param Buffer float
---@param IncreaseBuffer boolean
---@return boolean
function UABP_CH_MeshBase_C:AngleInRange(Angle, MinAngle, MaxAngle, Buffer, IncreaseBuffer) end
---@param Current MovementDirection::Type
---@param FR_Threshold float
---@param FL_Threshold float
---@param BR_Threshold float
---@param BL_Threshold float
---@param Buffer float
---@param Angle float
---@return MovementDirection::Type
function UABP_CH_MeshBase_C:CalculateQuadrant(Current, FR_Threshold, FL_Threshold, BR_Threshold, BL_Threshold, Buffer, Angle) end
---@param Current FLeanAmount
---@param Target FLeanAmount
---@param InterpSpeed float
---@param DeltaTime float
---@return FLeanAmount
function UABP_CH_MeshBase_C:InterpLeanAmount(Current, Target, InterpSpeed, DeltaTime) end
---@param Current FVelocityBlend
---@param Target FVelocityBlend
---@param InterpSpeed float
---@param DeltaTime float
---@return FVelocityBlend
function UABP_CH_MeshBase_C:InterpVelocityBlend(Current, Target, InterpSpeed, DeltaTime) end
---@param ShowTraceType EDrawDebugTrace::Type
---@param DebugType EDrawDebugTrace::Type
function UABP_CH_MeshBase_C:GetDebugTraceType(ShowTraceType, DebugType) end
function UABP_CH_MeshBase_C:DynamicTransitionCheck() end
function UABP_CH_MeshBase_C:RotateInPlaceCheck() end
---@param LeanAmount FLeanAmount
function UABP_CH_MeshBase_C:CalculateInAirLeanAmount(LeanAmount) end
---@param LandPrediction float
function UABP_CH_MeshBase_C:CalculateLandPrediction(LandPrediction) end
function UABP_CH_MeshBase_C:TurnInPlaceCheck() end
---@param TargetRotation FRotator
---@param PlayRateScale float
---@param StartTime float
---@param OverrideCurrent boolean
function UABP_CH_MeshBase_C:TurnInPlace(TargetRotation, PlayRateScale, StartTime, OverrideCurrent) end
---@return boolean
function UABP_CH_MeshBase_C:CanOverlayTransition() end
---@return boolean
function UABP_CH_MeshBase_C:CanDynamicTransition() end
---@return boolean
function UABP_CH_MeshBase_C:CanRotateInPlace() end
---@return boolean
function UABP_CH_MeshBase_C:CanTurnInPlace() end
---@param Return_Value boolean
function UABP_CH_MeshBase_C:ShouldMoveCheck(Return_Value) end
---@param LocalLocation FVector
---@param LocalRotation FRotator
function UABP_CH_MeshBase_C:SetFootLockOffsets(LocalLocation, LocalRotation) end
---@param Enable_FootIK_Curve FName
---@param FootLockCurve FName
---@param IKFootBone FName
---@param CurrentFootLockAlpha float
---@param CurrentFootLockLocation FVector
---@param CurrentFootLockRotation FRotator
function UABP_CH_MeshBase_C:SetFootLocking(Enable_FootIK_Curve, FootLockCurve, IKFootBone, CurrentFootLockAlpha, CurrentFootLockLocation, CurrentFootLockRotation) end
---@param CurrentLocationL_Target FVector
---@param CurrentLocationR_Target FVector
---@param CurrentLocationOffset FVector
---@param CurrentRotationOffset FRotator
function UABP_CH_MeshBase_C:SetFootOffsets(CurrentLocationL_Target, CurrentLocationR_Target, CurrentLocationOffset, CurrentRotationOffset) end
---@param ReturnValues MovementDirection::Type
function UABP_CH_MeshBase_C:CalculateMovementDirection(ReturnValues) end
---@param PlayRate float
function UABP_CH_MeshBase_C:CalculateCrouchingPlayRate(PlayRate) end
---@param PlayRate float
function UABP_CH_MeshBase_C:CalculateStandingPlayRate(PlayRate) end
---@return float
function UABP_CH_MeshBase_C:CalculateStrideBlend() end
---@param WalkRunBlend float
function UABP_CH_MeshBase_C:CalculateWalkRunBlend(WalkRunBlend) end
---@return FVector
UABP_CH_MeshBase_C['Calculate Relative Acceleration Amount'] = function(self, ) end
---@return float
function UABP_CH_MeshBase_C:CalculateDiagonalScaleAmount() end
---@return FVelocityBlend
function UABP_CH_MeshBase_C:CalculateVelocityBlend() end
function UABP_CH_MeshBase_C:UpdateRagdollValues() end
function UABP_CH_MeshBase_C:UpdateInAirValues() end
function UABP_CH_MeshBase_C:UpdateRotationValues() end
function UABP_CH_MeshBase_C:UpdateMovementValues() end
UABP_CH_MeshBase_C['Update Foot IK'] = function(self, ) end
function UABP_CH_MeshBase_C:UpdateLayerValues() end
UABP_CH_MeshBase_C['Update Character Info'] = function(self, ) end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_ModifyBone_DCB050404075A6D11CCAF9B7E8DC3039() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_ModifyBone_D230DF334EBA17502293E3A3AE03249E() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_LookAt_211191D44AE994690710A4851EFEAD22() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_BlendListByInt_27818ADC4EEE691D4D046093B5614F21() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_BlendListByInt_DB6122F54E607584944EF994199C8707() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_ModifyBone_E38F8FD54B0425E7972ADFA6FFDEED65() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_D6F93A464E6BAB795FC1119394BC8F49() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_072CDE8542978AECEF69879116FAF6C3() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_4079A1634C43683E49A8F8AA15C7B3EB() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_8AC7C0D94B7C5D1ED46FF29A99E1166F() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_3419A62A45DEC8A55FED899E00F783E5() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_9D02FC2E4C91D3CBC27D40BDACC6D51F() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_7C438D0F457C2E264E238FA09C9F007C() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_1A54E6ED44EB539483F3169042D1D9C5() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_198042894FFE1D3A4634A7A5B6B65C54() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_4B071AFA4E51734525FBB2A8B721DB85() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_E42C81AB4DF3911DB54AE0A3E1C40185() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_2B6BFB6443D826E14FD2478E86394F45() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_C1A4EDBA43432B3CB30140BF05AD7C9F() end
function UABP_CH_MeshBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_CH_MeshBase_AnimGraphNode_TransitionResult_274CDB9D48BE303F923DF0B7A4356B50() end
function UABP_CH_MeshBase_C:BlueprintInitializeAnimation() end
function UABP_CH_MeshBase_C:BlueprintBeginPlay() end
function UABP_CH_MeshBase_C:LoadEnd_ABP() end
---@param SinkingDistance float
function UABP_CH_MeshBase_C:SetSinkingDistance(SinkingDistance) end
---@param TargetActor AActor
function UABP_CH_MeshBase_C:SetLookAtTargetActor(TargetActor) end
---@param BoneName FString
function UABP_CH_MeshBase_C:SetLookAtTargetActorBoneName(BoneName) end
---@param LookAtType uint8
function UABP_CH_MeshBase_C:SetLookAtType(LookAtType) end
---@param Location FVector
function UABP_CH_MeshBase_C:SetLookAtWorldLocation(Location) end
---@param DeltaTimeX float
function UABP_CH_MeshBase_C:BlueprintUpdateAnimation(DeltaTimeX) end
UABP_CH_MeshBase_C['AnimNotify_->CLF Stop'] = function(self, ) end
function UABP_CH_MeshBase_C:AnimNotify_StopTransition() end
---@param Parameters FDynamicMontageParams
function UABP_CH_MeshBase_C:PlayTransition(Parameters) end
UABP_CH_MeshBase_C['AnimNotify_Roll->Idle'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_->N Stop L'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_->N Stop R'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Land->Idle'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_->N QuickStop '] = function(self, ) end
function UABP_CH_MeshBase_C:BPI_Jumped() end
---@param GroundedEntryState GroundedEntryState::Type
function UABP_CH_MeshBase_C:BPI_SetGroundedEntryState(GroundedEntryState) end
UABP_CH_MeshBase_C['AnimNotify_Reset-GroundedEntryState'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips F'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips B'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips LB'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips LF'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips RB'] = function(self, ) end
UABP_CH_MeshBase_C['AnimNotify_Hips RF'] = function(self, ) end
function UABP_CH_MeshBase_C:AnimNotify_Pivot() end
---@param ReTriggerDelay float
---@param Parameters FDynamicMontageParams
function UABP_CH_MeshBase_C:PlayDynamicTransition(ReTriggerDelay, Parameters) end
---@param OverlayOverrideState int32
function UABP_CH_MeshBase_C:BPI_SetOverlayOverrideState(OverlayOverrideState) end
---@param InAnimSeq UAnimSequence
function UABP_CH_MeshBase_C:SetOverrideLocomotionNotMoveAnim(InAnimSeq) end
function UABP_CH_MeshBase_C:AnimNotify_EnterMoving() end
function UABP_CH_MeshBase_C:AnimNotify_EnterIdle() end
function UABP_CH_MeshBase_C:UnlinkPhysics() end
function UABP_CH_MeshBase_C:LinkPhysics() end
---@param Enable boolean
UABP_CH_MeshBase_C['Set Saccade'] = function(self, Enable) end
---@param Enable boolean
UABP_CH_MeshBase_C['Set No Blink'] = function(self, Enable) end
function UABP_CH_MeshBase_C:AnimNotify_EnterStop() end
---@param EntryPoint int32
function UABP_CH_MeshBase_C:ExecuteUbergraph_ABP_CH_MeshBase(EntryPoint) end


