---@meta

---@class ABP_BtlTargetPanel_C : ABP_BtlGuiBaseActor_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field BtlGuiResources UBtlGuiResources
---@field BP_BtlDataBase UBP_BtlDataBase_C
---@field BtlGuiDraw UBtlGuiDrawComponent
---@field NavigationTimeline_L_Navigation_0BDC7B3446D2D0F3E26D879B2127402D FVector
---@field NavigationTimeline_L__Direction_0BDC7B3446D2D0F3E26D879B2127402D ETimelineDirection::Type
---@field NavigationTimeline_L UTimelineComponent
---@field NavigationTimeline_M_Navigation_A59790D745F623B87F47E18CE38BE93A FVector
---@field NavigationTimeline_M__Direction_A59790D745F623B87F47E18CE38BE93A ETimelineDirection::Type
---@field NavigationTimeline_M UTimelineComponent
---@field NavigationTimeline_S_Navigation_DD343CFF4D14C23D0C18C8B2BB97A5BB FVector
---@field NavigationTimeline_S__Direction_DD343CFF4D14C23D0C18C8B2BB97A5BB ETimelineDirection::Type
---@field NavigationTimeline_S UTimelineComponent
---@field AnimationWait_ScaleTrack_D65D6E794B560B08399FFFB15F9E78F3 FVector
---@field AnimationWait__Direction_D65D6E794B560B08399FFFB15F9E78F3 ETimelineDirection::Type
---@field AnimationWait UTimelineComponent
---@field AnimationStart_ScaleTrack_1AEB50754EB4B24B3962468140F9619A FVector
---@field AnimationStart__Direction_1AEB50754EB4B24B3962468140F9619A ETimelineDirection::Type
---@field AnimationStart UTimelineComponent
---@field NoDamageColorTimeline_NoDamageColor_837DDB2D49927A15BC0F418E2480B5EF FLinearColor
---@field NoDamageColorTimeline__Direction_837DDB2D49927A15BC0F418E2480B5EF ETimelineDirection::Type
---@field NoDamageColorTimeline UTimelineComponent
---@field EnemyElementCursorTimeline_InfoMarkScale_9BE4DD614FD9CB686096DAB849015DE4 float
---@field EnemyElementCursorTimeline_HPBarPos_9BE4DD614FD9CB686096DAB849015DE4 float
---@field EnemyElementCursorTimeline_CircleScale3_9BE4DD614FD9CB686096DAB849015DE4 float
---@field EnemyElementCursorTimeline_CircleScale2_9BE4DD614FD9CB686096DAB849015DE4 float
---@field EnemyElementCursorTimeline_CircleScale1_9BE4DD614FD9CB686096DAB849015DE4 float
---@field EnemyElementCursorTimeline__Direction_9BE4DD614FD9CB686096DAB849015DE4 ETimelineDirection::Type
---@field EnemyElementCursorTimeline UTimelineComponent
---@field EnemyFirstAnimTimeline_InfoMaskScale_2D107B454BFAA0F3A48469BEEE998AE6 float
---@field EnemyFirstAnimTimeline_HPBarPos_2D107B454BFAA0F3A48469BEEE998AE6 float
---@field EnemyFirstAnimTimeline_CircleScale3_2D107B454BFAA0F3A48469BEEE998AE6 float
---@field EnemyFirstAnimTimeline_CircleScale2_2D107B454BFAA0F3A48469BEEE998AE6 float
---@field EnemyFirstAnimTimeline_CircleScale1_2D107B454BFAA0F3A48469BEEE998AE6 float
---@field EnemyFirstAnimTimeline__Direction_2D107B454BFAA0F3A48469BEEE998AE6 ETimelineDirection::Type
---@field EnemyFirstAnimTimeline UTimelineComponent
---@field PlayerFirstAnimTimeline_InfoMarkScale_150BDF924A2CF82E41A012BC619AD562 float
---@field PlayerFirstAnimTimeline_HPBarPos_150BDF924A2CF82E41A012BC619AD562 float
---@field PlayerFirstAnimTimeline_CircleScale3_150BDF924A2CF82E41A012BC619AD562 float
---@field PlayerFirstAnimTimeline_CircleScale2_150BDF924A2CF82E41A012BC619AD562 float
---@field PlayerFirstAnimTimeline_CircleScale1_150BDF924A2CF82E41A012BC619AD562 float
---@field PlayerFirstAnimTimeline__Direction_150BDF924A2CF82E41A012BC619AD562 ETimelineDirection::Type
---@field PlayerFirstAnimTimeline UTimelineComponent
---@field PlayerAnimTimeline_PlayerAnim_0FDD5D3041EACF9AA408E8AC33AC4B52 float
---@field PlayerAnimTimeline__Direction_0FDD5D3041EACF9AA408E8AC33AC4B52 ETimelineDirection::Type
---@field PlayerAnimTimeline UTimelineComponent
---@field EnemyCommonAnimTimeline_EnemyCommonAnim_452FC8444616C79347398EAFBAB263A7 float
---@field EnemyCommonAnimTimeline__Direction_452FC8444616C79347398EAFBAB263A7 ETimelineDirection::Type
---@field EnemyCommonAnimTimeline UTimelineComponent
---@field Character ABP_BtlCharacterBase_C
---@field HPBarOffset FVector2D
---@field PosOffset FVector2D
---@field HPBarMask UBtlGuiDrawObjectRect
---@field IsHPBar boolean
---@field IsEnemy boolean
---@field EnemyCommonAnimParam float
---@field PlayerAnimParam float
---@field Sprite1 UBtlGuiDrawObjectSprite
---@field Sprite2 UBtlGuiDrawObjectSprite
---@field Sprite3 UBtlGuiDrawObjectSprite
---@field Sprite4 UBtlGuiDrawObjectSprite
---@field Sprite5 UBtlGuiDrawObjectSprite
---@field Scale1 float
---@field Scale2 float
---@field scale3 float
---@field ScaleOffset float
---@field HPBarPos float
---@field Sprite6 UBtlGuiDrawObjectSprite
---@field ScaleOffset2 float
---@field PrevCharacter ABP_BtlCharacterBase_C
---@field attr EBtlDataAttr
---@field WeakOffset FVector2D
---@field UnknownOffset FVector2D
---@field BlockOffset FVector2D
---@field scale4 float
---@field Sprite7 UBtlGuiDrawObjectSprite
---@field Sprite8 UBtlGuiDrawObjectSprite
---@field IconType int32
---@field IsMoving boolean
---@field OffsetTemp FVector2D
---@field MovingTime float
---@field OffsetTemp2 FVector2D
---@field GuiIcon ABP_BtlGuiIcon_C
---@field IsSaveSillhouette boolean
---@field CursorType int32
---@field BarMaxParam int32
---@field BarParam int32
---@field Sprite9 UBtlGuiDrawObjectSprite
---@field Sprite10 UBtlGuiDrawObjectSprite
---@field AbsorbOffset FVector2D
---@field ReflectOffset FVector2D
---@field IsShiftEnable boolean
---@field PlayerWeakOffset FVector2D
---@field ChkWeakSkill boolean
---@field NoDamageColor FColor
---@field ['Is Sillhouette Only'] boolean
---@field PBarPosLine float
---@field PBarPosLine2 float
---@field IsTutorial boolean
---@field CharacterComp UAppCharacterComp
---@field IsDamage boolean
---@field IsPhysical boolean
---@field skillId int32
---@field ['No Use Stensil'] boolean
---@field OutScale float
---@field InScale float
---@field Angle float
---@field ['Delay Stensil'] float
---@field IsDying boolean
---@field HPBar UBtlGuiDrawObjectSprite
---@field ['Delta TimeWork'] float
---@field SaveRenderCustomDepth_0 TArray<boolean>
---@field SaveCustomDepthStencilValue_0 TArray<int32>
---@field SaveWeaponRenderCustomDepth_0 TArray<boolean>
---@field SaveWeaponCustomDepthStencilValue_0 TArray<int32>
---@field SaveGunRenderCustomDepth_0 TArray<boolean>
---@field SaveGunCustomDepthStencilValue_0 TArray<int32>
---@field PrevIsEnemy boolean
local ABP_BtlTargetPanel_C = {}

---@param OutScale float
---@param InScale float
---@param Angle float
function ABP_BtlTargetPanel_C:GetSillhoetteAnimParam(OutScale, InScale, Angle) end
function ABP_BtlTargetPanel_C:StartAnimation() end
---@param Element EBtlDataAttr
---@param sprNo1 int32
---@param Color1 FColor
ABP_BtlTargetPanel_C['Get Element Offset'] = function(self, Element, sprNo1, Color1) end
---@param Action ABP_BtlCharacterBase_C
---@param SkipMovingAnimation boolean
function ABP_BtlTargetPanel_C:UpdateTarget(Action, SkipMovingAnimation) end
---@param Lerp float
---@param Pos FVector2D
function ABP_BtlTargetPanel_C:GetEnemyCursorCommonAnim(Lerp, Pos) end
---@param BtlCharacter ABP_BtlCharacterBase_C
---@param IsHPBar boolean
---@param IsSillhouetteOnly boolean
---@param NoUseStensil boolean
---@param DelayStensil float
function ABP_BtlTargetPanel_C:SetTarget(BtlCharacter, IsHPBar, IsSillhouetteOnly, NoUseStensil, DelayStensil) end
function ABP_BtlTargetPanel_C:UpdatePosition() end
function ABP_BtlTargetPanel_C:EnemyCommonAnimTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:EnemyCommonAnimTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:PlayerAnimTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:PlayerAnimTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:PlayerFirstAnimTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:PlayerFirstAnimTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:EnemyFirstAnimTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:EnemyFirstAnimTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:EnemyElementCursorTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:EnemyElementCursorTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:NoDamageColorTimeline__FinishedFunc() end
function ABP_BtlTargetPanel_C:NoDamageColorTimeline__UpdateFunc() end
function ABP_BtlTargetPanel_C:AnimationStart__FinishedFunc() end
function ABP_BtlTargetPanel_C:AnimationStart__UpdateFunc() end
function ABP_BtlTargetPanel_C:AnimationWait__FinishedFunc() end
function ABP_BtlTargetPanel_C:AnimationWait__UpdateFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_S__FinishedFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_S__UpdateFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_M__FinishedFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_M__UpdateFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_L__FinishedFunc() end
function ABP_BtlTargetPanel_C:NavigationTimeline_L__UpdateFunc() end
function ABP_BtlTargetPanel_C:StartEnemyCommonAnim() end
function ABP_BtlTargetPanel_C:StartPlayerAnim() end
function ABP_BtlTargetPanel_C:StartEnemyElementAnim() end
function ABP_BtlTargetPanel_C:StopSillhouetteAnim() end
function ABP_BtlTargetPanel_C:StartSillhouetteAnim() end
---@param DeltaTime float
function ABP_BtlTargetPanel_C:GuiActorUpdate(DeltaTime) end
function ABP_BtlTargetPanel_C:GuiActorBeginPlay() end
function ABP_BtlTargetPanel_C:GuiActorBeginDestroy() end
function ABP_BtlTargetPanel_C:CreateDrawItem() end
---@param EntryPoint int32
function ABP_BtlTargetPanel_C:ExecuteUbergraph_BP_BtlTargetPanel(EntryPoint) end


